# === Hardware configuration ===
PIN_SENSOR = 16
PIN_LED_RING = 17
PIN_OVERHEAD_LED = 18

RING_PIXEL_COUNT = 7
OVERHEAD_PIXEL_COUNT = 32

LED_RING_BRIGHTNESS = 1.0
OVERHEAD_LED_BRIGHTNESS = 1.0

# === PASSWORDS ===
SSID = "iPhone 13 Pro Max de Mate"
PASSWORD = "Mateoooo11..."

# === COLORS (R,G,B) ===
COLOR_OFF = (0, 0, 0)
COLOR_RED = (255, 0, 0)
COLOR_GREEN  = (0, 255, 0)
COLOR_BLUE = (0, 0, 255)
