# === Hardware configuration ===
PIN_SENSOR = 16
PIN_LED_RING = 18
PIN_OVERHEAD_LED = 18

PIXEL_COUNT_RING = 7
PIXEL_COUNT_OVERHEAD = 32

BRIGHTNESS_LED_RING = 1.0
BRIGHTNESS_OVERHEAD_LED = 1.0

# === PASSWORDS ===
SSID = "iPhone 13 Pro Max de Mate"
PASSWORD = "Mateoooo11..."

# === COLORS (R,G,B) ===
COLOR_OFF = (0, 0, 0)
COLOR_RED = (255, 0, 0)
COLOR_GREEN  = (0, 255, 0)
COLOR_BLUE = (0, 0, 255)
